package suts.desigenpattens.learnnote.data.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import suts.desigenpattens.learnnote.data.db.model.Option;
import suts.desigenpattens.learnnote.data.db.model.User;
import suts.desigenpattens.learnnote.data.db.model.Question;

import suts.desigenpattens.learnnote.data.db.greendao.OptionDao;
import suts.desigenpattens.learnnote.data.db.greendao.UserDao;
import suts.desigenpattens.learnnote.data.db.greendao.QuestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig optionDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig questionDaoConfig;

    private final OptionDao optionDao;
    private final UserDao userDao;
    private final QuestionDao questionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        optionDaoConfig = daoConfigMap.get(OptionDao.class).clone();
        optionDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        optionDao = new OptionDao(optionDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);

        registerDao(Option.class, optionDao);
        registerDao(User.class, userDao);
        registerDao(Question.class, questionDao);
    }
    
    public void clear() {
        optionDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        questionDaoConfig.clearIdentityScope();
    }

    public OptionDao getOptionDao() {
        return optionDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

}
